id: IB314D13C
default_language: fr
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:30.007141
last_modified: 2023-01-04 11:30:30.007155
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  BE1C:
    title: Words of Advice
    base_file: BE1C.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
